---
ReusePassword:
  description: ReusePassword
  value: 'true'
  group: feature_flags
  cast_type: boolean
RetryLimitExceeded:
  description: RetryLimitExceeded
  value: 'false'
  group: feature_flags
  cast_type: boolean
DeveloperMessage:
  description: DeveloperMessage
  value: Login succeeded
  group: feature_flag
  cast_type: string
UserMessage:
  description: UserMessage
  value: Login succeeded
  group: feature_flag
  cast_type: string
Version:
  description: Version
  value: '1'
  group: feature_flag
  cast_type: string
IsEmailValidated:
  description: IsEmailValidated
  value: 'true'
  group: feature_flag
  cast_type: boolean
LoginSucceeded:
  description: LoginSucceeded
  value: 'true'
  group: feature_flag
  cast_type: boolean
Status:
  description: Status
  value: OK
  group: feature_flag
  cast_type: string
RequestId:
  description: RequestId
  value: xxx
  group: feature_flag
  cast_type: string
